add test for pull#4347
add test for https://github.com/spree/spree/pull/4347#issuecomment-35351191
Just add a adjustment to order. 

```
Failures:

  1) Spree::Api::ShipmentsController as an admin can transition a shipment from ready to ship can transition a shipment from ready to ship
     Failure/Error: json_response.should have_attributes(attributes)
       expected {"exception"=>"undefined method `finalize!' for #<Spree::Adjustment:0x0000010db5b2c0>"} to have attributes [:id, :tracking, :number, :cost, :shipped_at, :stock_location_name, :order_id, :shipping_rates, :shipping_methods]
     # ./spec/controllers/spree/api/shipments_controller_spec.rb:105:in `block (4 levels) in <top (required)>'

Finished in 6.84 seconds
9 examples, 1 failure
```